import type { Metadata } from "next";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "300", "200", "800"],
  variable: "--font-poppins",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Header />
        <main className="py-4">
          <div className="max-w-5xl mx-auto px-4 border">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
